/*
 * OFD Checks API
 *
 * This is a OFD Checks API
 *
 * API version: 1.0.0
 * Contact: croacker@homeworld.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CheckItem struct {

	CheckHeader *CheckHeader `json:"checkHeader"`

	Product *Product `json:"product,omitempty"`

	Modifiers string `json:"modifiers,omitempty"`

	Price float32 `json:"price,omitempty"`

	Quantity float32 `json:"quantity,omitempty"`

	Sum float32 `json:"sum,omitempty"`

	Storno bool `json:"storno,omitempty"`

	Nds0 float32 `json:"nds0,omitempty"`

	Nds10 float32 `json:"nds10,omitempty"`

	Nds18 float32 `json:"nds18,omitempty"`

	NdsCalculated10 float32 `json:"ndsCalculated10,omitempty"`

	NdsCalculated18 float32 `json:"ndsCalculated18,omitempty"`

	NdsNo float32 `json:"ndsNo,omitempty"`
}
