/*
 * OFD Checks API
 *
 * This is a OFD Checks API
 *
 * API version: 1.0.0
 * Contact: croacker@homeworld.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/croacker/h-accounting/1.0.0/",
		Index,
	},

	Route{
		"AddCheckHeader",
		strings.ToUpper("Post"),
		"/croacker/h-accounting/1.0.0/check-header",
		AddCheckHeader,
	},

	Route{
		"AddCheckItem",
		strings.ToUpper("Post"),
		"/croacker/h-accounting/1.0.0/check-item",
		AddCheckItem,
	},

	Route{
		"AddPrice",
		strings.ToUpper("Post"),
		"/croacker/h-accounting/1.0.0/price",
		AddPrice,
	},

	Route{
		"AddProduct",
		strings.ToUpper("Post"),
		"/croacker/h-accounting/1.0.0/product",
		AddProduct,
	},

	Route{
		"AddProductCathegory",
		strings.ToUpper("Post"),
		"/croacker/h-accounting/1.0.0/product-cathegory",
		AddProductCathegory,
	},

	Route{
		"AddSailer",
		strings.ToUpper("Post"),
		"/croacker/h-accounting/1.0.0/sailer",
		AddSailer,
	},

	Route{
		"AddShop",
		strings.ToUpper("Post"),
		"/croacker/h-accounting/1.0.0/shop",
		AddShop,
	},

	Route{
		"DeleteCheckItem",
		strings.ToUpper("Delete"),
		"/croacker/h-accounting/1.0.0/check-item",
		DeleteCheckItem,
	},

	Route{
		"SearchCheckHeader",
		strings.ToUpper("Get"),
		"/croacker/h-accounting/1.0.0/check-header",
		SearchCheckHeader,
	},

	Route{
		"SearchCheckItem",
		strings.ToUpper("Get"),
		"/croacker/h-accounting/1.0.0/check-item",
		SearchCheckItem,
	},

	Route{
		"SearchPrice",
		strings.ToUpper("Get"),
		"/croacker/h-accounting/1.0.0/price",
		SearchPrice,
	},

	Route{
		"SearchProduct",
		strings.ToUpper("Get"),
		"/croacker/h-accounting/1.0.0/product",
		SearchProduct,
	},

	Route{
		"SearchProductCathegory",
		strings.ToUpper("Get"),
		"/croacker/h-accounting/1.0.0/product-cathegory",
		SearchProductCathegory,
	},

	Route{
		"SearchSailer",
		strings.ToUpper("Get"),
		"/croacker/h-accounting/1.0.0/sailer",
		SearchSailer,
	},

	Route{
		"SearchShop",
		strings.ToUpper("Get"),
		"/croacker/h-accounting/1.0.0/shop",
		SearchShop,
	},
}
